export const COUNTRY_TO_FLAG_CODE = {
  "Afghanistan": "AF",
  "Albania": "AL",
  "Algeria": "DZ",
  "American Samoa": "AS",
  "Andorra": "AD",
  "Angola": "AO",
  "Antigua": "AG",
  "Antigua and Barbuda": "AG",
  "Argentina": "AR",
  "Armenia": "AM",
  "Aruba": "AW",
  "Australia": "AU",
  "Austria": "AT",
  "Azerbaijan": "AZ",

  "Bahamas": "BS",
  "Bahrain": "BH",
  "Bangladesh": "BD",
  "Barbados": "BB",
  "Belarus": "BY",
  "Belgium": "BE",
  "Belize": "BZ",
  "Benin": "BJ",
  "Bermuda": "BM",
  "Bhutan": "BT",
  "Bolivia": "BO",
  "Bosnia": "BA",
  "Bosnia & Herzegovina": "BA",
  "Bosnia and Herzegovina": "BA",
  "Botswana": "BW",
  "Brazil": "BR",
  "Brunei": "BN",
  "Bulgaria": "BG",
  "Burkina Faso": "BF",
  "Burundi": "BI",

  "Cabo Verde": "CV",
  "Cambodia": "KH",
  "Cameroon": "CM",
  "Canada": "CA",
  "Cape Verde": "CV",
  "Cape Verde Islands": "CV",
  "Cayman Islands": "KY",
  "Central African Republic": "CF",
  "Chad": "TD",
  "Chile": "CL",
  "China": "CN",
  "China PR": "CN",
  "Chinese Taipei": "TW",
  "Colombia": "CO",
  "Comoros": "KM",
  "Congo": "CG",
  "Congo Republic": "CG",
  "Congo, DR": "CD",
  "Cook Islands": "CK",
  "Costa Rica": "CR",
  "Cote dIvoire": "CI",
  "Cote d'Ivoire": "CI",
  "Côte d'Ivoire": "CI",
  "Croatia": "HR",
  "Cuba": "CU",
  "Curaçao": "CW",
  "Curacao": "CW",
  "Cyprus": "CY",
  "Czech Republic": "CZ",
  "Czechia": "CZ",

  "DR Congo": "CD",
  "DPR Korea": "KP",
  "Denmark": "DK",
  "Democratic Republic Of The Congo": "CD",
  "Democratic Republic of the Congo": "CD",
  "Djibouti": "DJ",
  "Dominica": "DM",
  "Dominican Republic": "DO",

  "Ecuador": "EC",
  "Egypt": "EG",
  "El Salvador": "SV",
  "England": "GB-ENG",
  "Equatorial Guinea": "GQ",
  "Eritrea": "ER",
  "Estonia": "EE",
  "Eswatini": "SZ",
  "Ethiopia": "ET",

  "Faroe Islands": "FO",
  "Fiji": "FJ",
  "Finland": "FI",
  "France": "FR",

  "Gabon": "GA",
  "Gambia": "GM",
  "Georgia": "GE",
  "Germany": "DE",
  "Ghana": "GH",
  "Gibraltar": "GI",
  "Greece": "GR",
  "Grenada": "GD",
  "Guam": "GU",
  "Guatemala": "GT",
  "Guinea": "GN",
  "Guinea Bissau": "GW",
  "Guinea-Bissau": "GW",
  "Guyana": "GY",

  "Haiti": "HT",
  "Honduras": "HN",
  "Hong Kong": "HK",
  "Hungary": "HU",

  "IR Iran": "IR",
  "Iceland": "IS",
  "India": "IN",
  "Indonesia": "ID",
  "Iran": "IR",
  "Iraq": "IQ",
  "Ireland": "IE",
  "Israel": "IL",
  "Italy": "IT",
  "Ivory Coast": "CI",
  "Ivory coast": "CI",

  "Jamaica": "JM",
  "Japan": "JP",
  "Jordan": "JO",

  "Kazakstan": "KZ",
  "Kazakhstan": "KZ",
  "Kenya": "KE",
  "Korea DPR": "KP",
  "Korea Republic": "KR",
  "Korea, North": "KP",
  "Korea, South": "KR",
  "Kosovo": "XK",
  "Kuwait": "KW",
  "Kyrgyzstan": "KG",

  "Laos": "LA",
  "Latvia": "LV",
  "Lebanon": "LB",
  "Lesotho": "LS",
  "Liberia": "LR",
  "Libya": "LY",
  "Liechtenstein": "LI",
  "Lithuania": "LT",
  "Luxembourg": "LU",

  "Macau": "MO",
  "Macedonia": "MK",
  "Madagascar": "MG",
  "Malawi": "MW",
  "Malaysia": "MY",
  "Maldives": "MV",
  "Mali": "ML",
  "Malta": "MT",
  "Mauritania": "MR",
  "Mauritius": "MU",
  "Mexico": "MX",
  "Moldova": "MD",
  "Mongolia": "MN",
  "Montenegro": "ME",
  "Montserrat": "MS",
  "Morocco": "MA",
  "Mozambique": "MZ",
  "Myanmar": "MM",

  "Namibia": "NA",
  "Nepal": "NP",
  "Netherlands": "NL",
  "New Caledonia": "NC",
  "New Zealand": "NZ",
  "Nicaragua": "NI",
  "Niger": "NE",
  "Nigeria": "NG",
  "North Korea": "KP",
  "North Macedonia": "MK",
  "Northern Ireland": "GB-NIR",
  "Norway": "NO",

  "Oman": "OM",

  "Pakistan": "PK",
  "Palestine": "PS",
  "Panama": "PA",
  "Papua New Guinea": "PG",
  "Paraguay": "PY",
  "Peru": "PE",
  "Philippines": "PH",
  "Poland": "PL",
  "Portugal": "PT",
  "Puerto Rico": "PR",

  "Qatar": "QA",

  "Republic Of Ireland": "IE",
  "Republic of Ireland": "IE",
  "Republic of Korea": "KR",
  "Republic of the Congo": "CG",
  "Romania": "RO",
  "Russia": "RU",
  "Rwanda": "RW",

  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "Samoa": "WS",
  "San Marino": "SM",
  "Saudi Arabia": "SA",
  "Scotland": "GB-SCT",
  "Senegal": "SN",
  "Serbia": "RS",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Singapore": "SG",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Solomon Islands": "SB",
  "Somalia": "SO",
  "South Africa": "ZA",
  "South Korea": "KR",
  "South Sudan": "SS",
  "Spain": "ES",
  "Sri Lanka": "LK",
  "Sudan": "SD",
  "Suriname": "SR",
  "Swaziland": "SZ",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Syria": "SY",

  "Tahiti": "PF",
  "Taiwan": "TW",
  "Tajikistan": "TJ",
  "Tanzania": "TZ",
  "Thailand": "TH",
  "Timor Leste": "TL",
  "Timor-Leste": "TL",
  "Togo": "TG",
  "Tonga": "TO",
  "Trinidad and Tobago": "TT",
  "Tunisia": "TN",
  "Turkey": "TR",
  "Turkiye": "TR",
  "Türkiye": "TR",
  "Turkmenistan": "TM",
  "Turks and Caicos Islands": "TC",

  "U.S.A.": "US",
  "UAE": "AE",
  "USA": "US",
  "Uganda": "UG",
  "Ukraine": "UA",
  "United Arab Emirates": "AE",
  "United States": "US",
  "United States of America": "US",
  "Uruguay": "UY",
  "US Virgin Islands": "VI",
  "Uzbekistan": "UZ",

  "Vanuatu": "VU",
  "Venezuela": "VE",
  "Vietnam": "VN",

  "Wales": "GB-WLS",

  "Yemen": "YE",

  "Zambia": "ZM",
  "Zimbabwe": "ZW"
};

export function countryToFlagCode(country) {
  const clean = String(country || "")
    .trim()
    .replace(/\s+/g, " ");

  return COUNTRY_TO_FLAG_CODE[clean] || "";
}