const DIRECT_FLAG_OVERRIDES = {
  england: "🏴",
  scotland: "🏴",
  wales: "🏴",
  "northern ireland": "🇬🇧",
  kosovo: "🇽🇰",
};

const COUNTRY_TO_CODE = {
  afghanistan: "AF",
  albania: "AL",
  algeria: "DZ",
  andorra: "AD",
  angola: "AO",
  antiguaandbarbuda: "AG",
  argentina: "AR",
  armenia: "AM",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bahamas: "BS",
  bahrain: "BH",
  bangladesh: "BD",
  barbados: "BB",
  belarus: "BY",
  belgium: "BE",
  belize: "BZ",
  benin: "BJ",
  bhutan: "BT",
  bolivia: "BO",
  "boliviaplurinationalstateof": "BO",
  bosniaandherzegovina: "BA",
  botswana: "BW",
  brazil: "BR",
  brunei: "BN",
  "bruneidarussalam": "BN",
  bulgaria: "BG",
  burkinafaso: "BF",
  burundi: "BI",
  caboverde: "CV",
  "capeverde": "CV",
  cambodia: "KH",
  cameroon: "CM",
  canada: "CA",
  centralafricanrepublic: "CF",
  chad: "TD",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  comoros: "KM",
  congo: "CG",
  "republicofthecongo": "CG",
  "democraticrepublicofthecongo": "CD",
  "drcongo": "CD",
  costarica: "CR",
  croatia: "HR",
  cuba: "CU",
  cyprus: "CY",
  czechia: "CZ",
  "czechrepublic": "CZ",
  denmark: "DK",
  djibouti: "DJ",
  dominica: "DM",
  dominicanrepublic: "DO",
  ecuador: "EC",
  egypt: "EG",
  elsalvador: "SV",
  equatorialguinea: "GQ",
  eritrea: "ER",
  estonia: "EE",
  eswatini: "SZ",
  swaziland: "SZ",
  ethiopia: "ET",
  fiji: "FJ",
  finland: "FI",
  france: "FR",
  gabon: "GA",
  gambia: "GM",
  georgia: "GE",
  germany: "DE",
  ghana: "GH",
  greece: "GR",
  grenada: "GD",
  guatemala: "GT",
  guinea: "GN",
  guineabissau: "GW",
  guyana: "GY",
  haiti: "HT",
  honduras: "HN",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  "irislamicrepublicof": "IR",
  iraq: "IQ",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  ivorycoast: "CI",
  "cotedivoire": "CI",
  jamaica: "JM",
  japan: "JP",
  jordan: "JO",
  kazakhstan: "KZ",
  kenya: "KE",
  kiribati: "KI",
  kuwait: "KW",
  kyrgyzstan: "KG",
  laos: "LA",
  "laopeoplesdemocraticrepublic": "LA",
  latvia: "LV",
  lebanon: "LB",
  lesotho: "LS",
  liberia: "LR",
  libya: "LY",
  liechtenstein: "LI",
  lithuania: "LT",
  luxembourg: "LU",
  madagascar: "MG",
  malawi: "MW",
  malaysia: "MY",
  maldives: "MV",
  mali: "ML",
  malta: "MT",
  marshallislands: "MH",
  mauritania: "MR",
  mauritius: "MU",
  mexico: "MX",
  micronesia: "FM",
  "federatedstatesofmicronesia": "FM",
  moldova: "MD",
  "moldovarepublicof": "MD",
  monaco: "MC",
  mongolia: "MN",
  montenegro: "ME",
  morocco: "MA",
  mozambique: "MZ",
  myanmar: "MM",
  burma: "MM",
  namibia: "NA",
  nauru: "NR",
  nepal: "NP",
  netherlands: "NL",
  newzealand: "NZ",
  nicaragua: "NI",
  niger: "NE",
  nigeria: "NG",
  "northkorea": "KP",
  "democraticpeoplesrepublicofkorea": "KP",
  "southkorea": "KR",
  "korearepublic": "KR",
  norway: "NO",
  oman: "OM",
  pakistan: "PK",
  palau: "PW",
  palestine: "PS",
  panama: "PA",
  papuanewguinea: "PG",
  paraguay: "PY",
  peru: "PE",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  qatar: "QA",
  romania: "RO",
  russia: "RU",
  "russianfederation": "RU",
  rwanda: "RW",
  saintkittsandnevis: "KN",
  saintlucia: "LC",
  saintvincentandthegrenadines: "VC",
  samoa: "WS",
  sanmarino: "SM",
  saotomeandprincipe: "ST",
  saudiarabia: "SA",
  senegal: "SN",
  serbia: "RS",
  seychelles: "SC",
  sierraleone: "SL",
  singapore: "SG",
  slovakia: "SK",
  slovenia: "SI",
  solomonislands: "SB",
  somalia: "SO",
  southafrica: "ZA",
  southsudan: "SS",
  spain: "ES",
  srilanka: "LK",
  sudan: "SD",
  suriname: "SR",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  "syrianarabrepublic": "SY",
  taiwan: "TW",
  tajikistan: "TJ",
  tanzania: "TZ",
  "unitedrepublicoftanzania": "TZ",
  thailand: "TH",
  timorleste: "TL",
  "easttimor": "TL",
  togo: "TG",
  tonga: "TO",
  trinidadandtobago: "TT",
  tunisia: "TN",
  turkey: "TR",
  turkiye: "TR",
  turkmenistan: "TM",
  tuvalu: "TV",
  uganda: "UG",
  ukraine: "UA",
  unitedarabemirates: "AE",
  uae: "AE",
  unitedkingdom: "GB",
  uk: "GB",
  greatbritain: "GB",
  britain: "GB",
  england: "GB",
  scotland: "GB",
  wales: "GB",
  "northernireland": "GB",
  unitedstates: "US",
  "unitedstatesofamerica": "US",
  usa: "US",
  uruguay: "UY",
  uzbekistan: "UZ",
  vanuatu: "VU",
  vaticancity: "VA",
  "holysee": "VA",
  venezuela: "VE",
  "venezuelabolivarianrepublicof": "VE",
  vietnam: "VN",
  yemen: "YE",
  zambia: "ZM",
  zimbabwe: "ZW",
};

function normalizeCountryName(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[.'’-]/g, "")
    .replace(/\s+/g, "");
}

function codeToFlagEmoji(code) {
  if (!code || code.length !== 2) return "";
  return String.fromCodePoint(
    ...code
      .toUpperCase()
      .split("")
      .map((char) => 127397 + char.charCodeAt(0))
  );
}

export function countryToFlagEmoji(country) {
  const key = normalizeCountryName(country);
  if (!key) return "";

  if (DIRECT_FLAG_OVERRIDES[key]) return DIRECT_FLAG_OVERRIDES[key];

  const code = COUNTRY_TO_CODE[key];
  return code ? codeToFlagEmoji(code) : "";
}

export function countryWithFlag(country) {
  const clean = String(country || "").trim();
  if (!clean) return "";

  const flag = countryToFlagEmoji(clean);
  return flag ? `${flag} ${clean}` : clean;
}